version: '3.8'

services:
  web:
    build: ./services/yt-api
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/yt-api/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
