version: '3.8'

services:
  web:
    build: ./services/yt-api
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/yt-api/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

  redis:
    image: redis:alpine
    command: redis-server

  celery:
    build: ./services/yt-api
    command: celery -A project.celery_app worker -l info -E
    volumes:
      - ./services/yt-api/:/usr/src/app/
    environment:
      - ./.env.dev
    depends_on:
      - redis

  celery-beat:
    build: ./services/yt-api
    command: celery -A project.celerybeat beat -l info
    volumes:
      - ./services/yt-api/:/usr/src/app/
    environment:
      - ./.env.dev
    depends_on:
      - redis

volumes:
  postgres_data: